### ISSUE TITLE
Is it possible to model scenes in a blender project? 

### ISSUE THREAD

**Issue by Rlee719** [Linxius/UrbanScene3D#8]
Hi, I was wondering if it's possible to export the scenes to a blender project so we can easily edit the scene? I would appreciate it if any guidelines for doing this are mentioned. 

Thanks in advance!

**Comment by Linxius** [comment]
The models of the large-scale virtual scenes are not provided due to the copyright issue and the textured meshes can not be exported from UE. We provide sampled points for them for evaluation purpose (https://github.com/Linxius/UrbanScene3D/releases/download/v0.0.1/UrbanScene3D-virtual_cities-sampled.7z).

**Comment by Rlee719** [comment]
> The models of the large-scale virtual scenes are not provided due to the copyright issue and the textured meshes can not be exported from UE. We provide sampled points for them for evaluation purpose (https://github.com/Linxius/UrbanScene3D/releases/download/v0.0.1/UrbanScene3D-virtual_cities-sampled.7z).

Got it, thank you!
